"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import { usePathname } from "next/navigation";
import Link from 'next/link';
import { routePath } from "./const/routePath";
import { AntdRegistry } from '@ant-design/nextjs-registry';
// import { Comforter_Brush } from 'next/font/google'   设置全局字体
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// 通过内置的google字体来设置全局字体
// export const roboto_mono = Comforter_Brush({
//   subsets: ['latin'],
//   weight: '400',
// })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // usePathname获取当前路由
  const pathname = usePathname();
  // console.log('pathname: ', pathname);
  return (
    <html lang="en">
      {/* 根layout  必须有的*/}
      {/* 在body的className里面增加引入的字体样式${roboto_mono.className} */}
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Link href={'/'}>
              <span style={{color: pathname === routePath.home ?  '#1b62d580' : 'black' }}>· index page </span> 
          </Link>
          <br/>
          <Link href={'/LayoutDashboard'}>
            <span style={{color: pathname === routePath.layoutDashboard ?  '#1b62d580' : 'black' }}>· LayoutDashboard page</span> 
          </Link>
          <br/>
          <Link href={'/LayoutDashboard/settings'}>
            <span style={{color: pathname === routePath.layoutDashboardSettings ?  '#1b62d580' : 'black' }}>· LayoutDashboard template- settings  page</span> 
          </Link>
          <br/>
          <Link href={'/LayoutDashboard/about'}>
            <span style={{color: pathname === routePath.layoutDashboardAbout ?  '#1b62d580' : 'black' }}>· LayoutDashboard template- about  page</span> 
          </Link>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
